# Bienvenidos

Esto es un notebook. Podemos escribir en lenguaje Markdown, el cual nos permite:
* Listas
* Podemos escribir
* Escribir en **negrita** y *cursiva*
* Más información aquí: [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)


### PREGUNTAD!!

Sobretodo si os perdeis, no lleguemos a casos donde no sepais que estamos haciendo.

![Imagen no cargada. Edita y borra la @ ](https://img.buzzfeed.com/buzzfeed-static/static/2014-10/26/6/enhanced/webdr08/longform-original-14836-1414320930-10.jpg )

# Introducción

![ ](diagrama_resumen.png)

# Bibliografía 

Sobre **estadística**: [Practical Statistics for Data Scientists: 50 Essential Concepts](https://www.amazon.com/Practical-Statistics-Data-Scientists-Essential/dp/1491952962/ref=sr_1_3?ie=UTF8&qid=1518719786)


Sobre **R**: [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1491910399/ref=sr_1_1?ie=UTF8&qid=1518791084) Este libro es bastante completo, abarca mucho temario que no veremos por falta de tiempo.
                    


## Estadística vs Machine Learning


Más información aquí: [Markdown-Cheatsheet](https://www.reddit.com/r/MachineLearningLounge/comments/9soaw4/let_me_fix_that_for_you/)


* Estadística: Trata de entender las variables y su relación entre ellas. Las estadísitcas te ayudan a entender como es tu población de datos.

* Machine Learning: Trata de hacer predicciones, crear modelos que, a partir de una población limitada puedan **generalizar** y aprender como se comportarán los datos.



# Introducción a R

R es un lenguaje de programación orientado a la estadística.

Algo parecido a SPSS o Matlab.

Es código abierto y se entrega bajo licencia GPL (versión 2 o posterior). Además existen multitud de paquetes que complementan su funcionalidad.

## Asignaciones

Podemos usar <- o el símbolo = para asignar un valor a una variable

In [1]:
a = 5

In [2]:
print(a)

[1] 5


In [3]:
a

[1] 5

In [10]:
print("Hola mundo")

[1] "Hola mundo"


In [11]:
b <- 2
print(b)
c <--3
print(c)

[1] 2
[1] -3


## Operaciones

In [13]:
a
b

a+b #Suma

a^b #potencia

a %% b #módulo

a / b # División

a - b # Resta


[1] 5

[1] 2

[1] 7

[1] 25

[1] 1

[1] 2.5

[1] 3

## Funciones básicas

Las funciones 
 * siempre acaban en ()
 * pueden recibir un número variable de parámetros
 * pueden existir parámetros por defecto

Ver las variables en memoria, función ls()

In [14]:
ls()

[1] "a" "b" "c"

Ver el tipo de variable, función typeof(x):

In [15]:
typeof(a)

[1] "double"

# Tipos de datos

## double

In [16]:
a<-2018
a
typeof(a)

[1] 2018

[1] "double"

In [17]:
b<-exp(1)
b

[1] 2.718282

In [19]:
?exp

## integer

In [21]:
ai<-as.integer(3.789)
ai
typeof(ai)

[1] 3

[1] "integer"

## Diferencias entre  integer y double

El número más grande que podemos representar es diferente:

In [22]:
.Machine$integer.max
.Machine$double.xmax

[1] 2147483647

[1] 1.797693e+308

El tamaño que ocupan en memoria es:

In [23]:
object.size(ai)
object.size(b)

56 bytes

56 bytes

## character

In [25]:
s1<-' Discovery'
s1
typeof(s1)

[1] " Discovery"

[1] "character"

Las cadenas de texto se pueden concatenar usando la función paste(x,y,z...)

In [26]:
?paste

In [28]:
paste(s1,"Loca","Tardigrado",sep="------")

[1] " Discovery------Loca------Tardigrado"

## Logical

In [31]:
b1 <- TRUE
b2 <- T
b3 <- FALSE
paste("El valor de b1 es",b1)
paste("El valor de b2 es",b2)
paste("El valor de b3 es",b3)

[1] "El valor de b1 es TRUE"

[1] "El valor de b2 es TRUE"

[1] "El valor de b3 es FALSE"

In [32]:
print(paste("b1 AND b3:",b1 & b3))
print(paste("b1 OR  b3:",b1 | b3))
print(paste("b1 XOR b3:",xor(b1 ,b3)))
print(paste("   NOT b1:",!b1))

[1] "b1 AND b3: FALSE"
[1] "b1 OR  b3: TRUE"
[1] "b1 XOR b3: TRUE"
[1] "   NOT b1: FALSE"


## Vectores

Los vectores se crean con la función c(), todos los elementos de un vector son del mimo tipo. Es decir, no se podrían mezclar caracteres y double.

En python:

   a = [1,2,3,40]
   
En R:

   a = c(1,2,3,40)

In [37]:
?c

In [34]:
c(1,2,4,7,8)

[1] 1 2 4 7 8

In [35]:
alturas<-c(1.80,1.60,1.50,1.90,1.75,1.63,1.65)
print(paste("alturas es una variable de tipo:",typeof(alturas)))

[1] "alturas es una variable de tipo: double"


In [36]:
print("Podemos ver la estructura de un objeto con la función str():")
str(alturas)

[1] "Podemos ver la estructura de un objeto con la función str():"
 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [39]:
otroVector <- c("uno",2.0,"tres","14.0")
otroVector

[1] "uno"  "2"    "tres" "14.0"

In [40]:
str(otroVector)

 chr [1:4] "uno" "2" "tres" "14.0"


### Acceso a elementos

In [41]:
print(paste("El valor del tercer elemento es:",alturas[3]))

[1] "El valor del tercer elemento es: 1.5"


**¡¡En R los arrays empiezan en 1!!**
![Imagen no cargada. Edita y borra la @ ](https://i.redd.it/iwnqgrrbls5z.png @ )

Podemos dar nombres a cada elemento

In [42]:
myVector <- c(nombre="Philip",apellido="García",teléfono=600100100)

In [43]:
myVector

nombre    apellido    teléfono 
   "Philip"    "García" "600100100"

In [44]:
str(myVector)

 Named chr [1:3] "Philip" "García" "600100100"
 - attr(*, "names")= chr [1:3] "nombre" "apellido" "teléfono"


In [48]:
myVector["apellido"]

apellido 
"García"

In [49]:
myVector[2]

apellido 
"García"

In [50]:
myVector["teléfono"]

teléfono 
"600100100"

In [51]:
#Los nombres de una variable se pueden ver con la función names()
names(myVector)

[1] "nombre"   "apellido" "teléfono"

In [52]:
?names

In [57]:
names(myVector) <- c("nombre_actualizado","apellido_actualizado", "telefono_actualizado")

In [58]:
myVector

nombre_actualizado apellido_actualizado telefono_actualizado 
            "Philip"             "García"          "600100100"

### Operaciones con vectores

Al operar contra una variable se aplica esa operación a todos los elementos del vector

In [59]:
metro2pie <- 3.28084
alturasEnPies <- alturas*metro2pie
alturasEnPies

[1] 5.905512 5.249344 4.921260 6.233596 5.741470 5.347769 5.413386

Si se opera con dos vectores de la misma longitud se aplica elemento a elemento.

In [61]:
alturas

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65

In [64]:
alturaDeLosZapatos<-c(2,0,1,3,5,7,0)/100

alturaReal<-alturas-alturaDeLosZapatos
alturaReal

[1] 1.78 1.60 1.49 1.87 1.70 1.56 1.65

Se puede operar con vectores de tamaños diferentes, en este caso el vector más pequeño se replica

In [67]:
alturas*c(1,0)

Warning message in alturas * c(1, 0):
“longer object length is not a multiple of shorter object length”

[1] 1.80 0.00 1.50 0.00 1.75 0.00 1.65

Concatenar vectores

In [76]:
c(alturas,2,1.8,17)

[1]  1.80  1.70  1.50  1.90  1.75  1.63  1.65  2.00  1.80 17.00

Longitud de un vector se obtiene con la función length()

In [69]:
length(alturas)

[1] 7

La estructura de la variable se puede ver con la función str()

In [70]:
str(alturas)

 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [74]:
#Para modificar un valor
alturas[2]<-1.7
alturas

[1] 1.80 1.70 1.50 1.90 1.75 1.63 1.65

In [77]:
alturas[18]<-1.9

In [78]:
alturas

[1] 1.80 1.70 1.50 1.90 1.75 1.63 1.65   NA   NA   NA   NA   NA   NA   NA   NA
[16]   NA   NA 1.90

## Listas

Las listas se pueden considerar como vectores que pueden almacenar cualquier tipo de dato.

In [79]:
c(1,3,"catorce","panama")

[1] "1"       "3"       "catorce" "panama"

In [80]:
myList<-list(1,3,"catorce","panama")
str(myList)

List of 4
 $ : num 1
 $ : num 3
 $ : chr "catorce"
 $ : chr "panama"


In [81]:
myList

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] "catorce"

[[4]]
[1] "panama"

Podemos asignar un nombre a cada valor

In [84]:
datosPersonales<-list(nombre="Philip",
                   apellido="García",
                   teléfono=600100100)
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

In [85]:
str(datosPersonales)

List of 3
 $ nombre  : chr "Philip"
 $ apellido: chr "García"
 $ teléfono: num 6e+08


### Acceso a elementos

Podemos acceder a los distintos elementos utilizando su índice o nombre:

In [91]:
datosPersonales[[1]]

[1] "Philip"

In [92]:
datosPersonales[["nombre"]]

[1] "Philip"

In [99]:
datosPersonales$direccion

NULL

In [100]:
is.null(datosPersonales[["direccion"]])

[1] TRUE

In [105]:
?is.null

In [106]:
names(datosPersonales)

[1] "nombre"   "apellido" "teléfono"

In [107]:
datosPersonales[["direccion"]]<-list(ciudad="Madrid",calle="Desengaño",numero=21)
datosPersonales[["direccion"]]

$ciudad
[1] "Madrid"

$calle
[1] "Desengaño"

$numero
[1] 21

In [108]:
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

$direccion
$direccion$ciudad
[1] "Madrid"

$direccion$calle
[1] "Desengaño"

$direccion$numero
[1] 21

In [116]:
datosPersonales[["direccion"]]$calle

[1] "Desengaño"

In [117]:
print(paste("La longitud total de la lista es",length(datosPersonales)))

[1] "La longitud total de la lista es 4"


In [123]:
print(paste("La longitud del campo dirección",length(datosPersonales$d)))

[1] "La longitud del campo dirección 3"


## Factores

Útiles cuando trabajamos con variables categóricas. Ej: Población de origen, colores, sabores

In [125]:
saboresDePlatos<-c("Dulce","Salado","Ácido","Amargo","Umami","Dulce","Salado","Ácido","Umami","Umami","Salado")
saboresDePlatosFactor<-factor(saboresDePlatos)

summary(saboresDePlatos)
summary(saboresDePlatosFactor)

   Length     Class      Mode 
       11 character character 

Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3

In [126]:
str(saboresDePlatos)

 chr [1:11] "Dulce" "Salado" "Ácido" "Amargo" "Umami" "Dulce" "Salado" ...


In [127]:
str(saboresDePlatosFactor)

 Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


In [128]:
saboresDePlatosFactor

[1] Dulce  Salado Ácido  Amargo Umami  Dulce  Salado Ácido  Umami  Umami 
[11] Salado
Levels: Ácido Amargo Dulce Salado Umami

In [132]:
print("Los factores internamente se gestionan como enteros")
as.numeric(saboresDePlatosFactor)

[1] "Los factores internamente se gestionan como enteros"


[1] 3 4 1 2 5 3 4 1 5 5 4

In [139]:
levels(saboresDePlatosFactor)

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [130]:
paste("sabor:",levels(saboresDePlatosFactor))

[1] "sabor: Ácido"  "sabor: Amargo" "sabor: Dulce"  "sabor: Salado"
[5] "sabor: Umami"

In [146]:
paste("texto1","texto2","texto4",sep="----")
paste(c("texto1","texto2","texto4"),collapse="----")

[1] "texto1----texto2----texto4"

[1] "texto1----texto2----texto4"

In [140]:
print(paste("Podemos ver los niveles con el comando levels:",
            paste(levels(saboresDePlatosFactor),collapse=",")))

[1] "Podemos ver los niveles con el comando levels: Ácido,Amargo,Dulce,Salado,Umami"


In [149]:
factor(c(1,0,0,1,0,1),labels=c("NO","SI"))

[1] SI NO NO SI NO SI
Levels: NO SI

In [134]:
s<-factor(c(10,5,5,0,5,0),labels=c("BAJO","MEDIO","ALTO"))
s

[1] ALTO  MEDIO MEDIO BAJO  MEDIO BAJO 
Levels: BAJO MEDIO ALTO

In [135]:
as.numeric(s)

[1] 3 2 2 1 2 1

# Matrices

Podemos crear matrices con la función matrix. Como parámetros de entrada recibe un vector y el número de columnas (*ncol*) o filas (nrow). Un parámetro opcional (*byrow*) indica si la matriz se va a rellenar por filas o por columnas (valor por defecto)

In [151]:
c(1:12)

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [155]:
m1<-matrix(c(1:12),ncol=3)
m1

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [156]:
?matrix

In [165]:
m2<-matrix(c(1:12),ncol=3,byrow=T)
m2

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

La dimensión del array se puede ver con la función *dim()* o con *str()*

In [158]:
dim(m1)

[1] 4 3

In [159]:
length(m1)

[1] 12

In [160]:
str(m2)

 int [1:4, 1:3] 1 4 7 10 2 5 8 11 3 6 ...


### Acceso

El acceso se realiza igual que los vectores, pero aquí tenemos dos dimensiones.

In [167]:
m1[2,3]

[1] 10

También podemos dar nombres a las filas y columnas para luego poder acceder utilizando el nombre

In [168]:
?paste0

In [170]:
paste0("text1","text2")
paste("text1","text2",sep="")

[1] "text1text2"

[1] "text1text2"

In [171]:
paste0("row",1:4)

[1] "row1" "row2" "row3" "row4"

In [172]:
colnames(m1)<-paste0("col",1:3)
rownames(m1)<-paste0("row",1:4)
m1

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

In [181]:
paste("El valor de \"row1\" y 'col3' es:",m1["row1","col3"])
paste('El valor de "row1" y \'col3\' es:',m1[1,3])

[1] "El valor de \"row1\" y 'col3' es: 9"

[1] "El valor de \"row1\" y 'col3' es: 9"

Las funciones *colnames* y *rownames* 

In [175]:
rownames(m1)

[1] "row1" "row2" "row3" "row4"

In [176]:
colnames(m1)

[1] "col1" "col2" "col3"

### Operaciones con matrices 
#### Álgebra lineal básica

In [182]:
m1

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

Transpuesta

In [183]:
t(m1)

row1 row2 row3 row4
col1 1     2    3    4  
col2 5     6    7    8  
col3 9    10   11   12

Suma de constante

In [186]:
m1+10

col1 col2 col3
row1 11   15   19  
row2 12   16   20  
row3 13   17   21  
row4 14   18   22

Suma de matrices

In [189]:
m1
m2

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [188]:
m1+m2

col1 col2 col3
row1  2    7   12  
row2  6   11   16  
row3 10   15   20  
row4 14   19   24

In [190]:
m1
matrix(rep(1,12),nrow=3)

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 1    1    1    1   
[3,] 1    1    1    1

Multiplicación de matrices

In [193]:
m1 %*% matrix(rep(1,12),nrow=3)

[,1] [,2] [,3] [,4]
row1 15   15   15   15  
row2 18   18   18   18  
row3 21   21   21   21  
row4 24   24   24   24

In [202]:
rep("a",5)

[1] "a" "a" "a" "a" "a"

Submatrices

In [203]:
m1[2:4,2:3]

col2 col3
row2 6    10  
row3 7    11  
row4 8    12

In [204]:
m1[c(3,2,4),2:3]

col2 col3
row3 7    11  
row2 6    10  
row4 8    12

# Tablas

Se utilizan para estudios de frecuencia. Cuentan el número de veces que ha ocurrido algo.

In [205]:
saboresDePlatos

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

In [218]:
str(summary(saboresDePlatosFactor))

 Named int [1:5] 2 1 2 3 3
 - attr(*, "names")= chr [1:5] "Ácido" "Amargo" "Dulce" "Salado" ...


In [219]:
str(c(acido=2,amargo=1,dulce=2,salado=3,unami=3))

 Named num [1:5] 2 1 2 3 3
 - attr(*, "names")= chr [1:5] "acido" "amargo" "dulce" "salado" ...


In [215]:
tblSabores<-table(saboresDePlatosFactor)
tblSabores

saboresDePlatosFactor
 Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3 

In [210]:
names(tblSabores)

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [211]:
str(tblSabores)

 'table' int [1:5(1d)] 2 1 2 3 3
 - attr(*, "dimnames")=List of 1
  ..$ saboresDePlatos: chr [1:5] "Ácido" "Amargo" "Dulce" "Salado" ...


Los atributos son una lista de propiedades asociadas a un objeto en R

In [216]:
attributes(tblSabores)

$dim
[1] 5

$dimnames
$dimnames$saboresDePlatosFactor
[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami" 


$class
[1] "table"

In [220]:
class(tblSabores)

[1] "table"

In [222]:
str(unclass(tblSabores))

 int [1:5(1d)] 2 1 2 3 3
 - attr(*, "dimnames")=List of 1
  ..$ saboresDePlatosFactor: chr [1:5] "Ácido" "Amargo" "Dulce" "Salado" ...


In [223]:
attributes(tblSabores)$dimnames$saboresDePlatos 

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [224]:
color  <- c("marrón","negro","blanco","negro","blanco","negro","negro","marrón","marrón","marrón")
animal <- c("gato","gato","perro","gato","gato","perro","perro","perro","gato","gato")

tbl_animal<-table(animal,color)
tbl_animal

       color
animal  blanco marrón negro
  gato       1      3     2
  perro      1      1     2

In [234]:
tbl_animal[2,3]
tbl_animal["perro","negro"]

[1] 2

[1] 2

In [225]:
str(tbl_animal)

 'table' int [1:2, 1:3] 1 1 3 1 2 2
 - attr(*, "dimnames")=List of 2
  ..$ animal: chr [1:2] "gato" "perro"
  ..$ color : chr [1:3] "blanco" "marrón" "negro"


In [226]:
attributes(tbl_animal)$dimnames

$animal
[1] "gato"  "perro"

$color
[1] "blanco" "marrón" "negro"

In [227]:
attributes(tbl_animal)

$dim
[1] 2 3

$dimnames
$dimnames$animal
[1] "gato"  "perro"

$dimnames$color
[1] "blanco" "marrón" "negro" 


$class
[1] "table"

## Miniresumen parcial

Vector

In [238]:
vecto_pesos <- c(5,7,8,9,10)
vecto_pesos[2:length(vecto_pesos)]

[1]  7  8  9 10

Listas

In [239]:
lista_medidas <- list(altura=1.5, ancho=1, peso = 3, unidades_peso="Kg", unidades_medida="m", 
                      fabricacion=list(numeroserie="A1238656", origen="Zamora"))
lista_medidas

$altura
[1] 1.5

$ancho
[1] 1

$peso
[1] 3

$unidades_peso
[1] "Kg"

$unidades_medida
[1] "m"

$fabricacion
$fabricacion$numeroserie
[1] "A1238656"

$fabricacion$origen
[1] "Zamora"

In [243]:
str(lista_medidas)

List of 6
 $ altura         : num 1.5
 $ ancho          : num 1
 $ peso           : num 3
 $ unidades_peso  : chr "Kg"
 $ unidades_medida: chr "m"
 $ fabricacion    :List of 2
  ..$ numeroserie: chr "A1238656"
  ..$ origen     : chr "Zamora"


In [242]:
lista_medidas[["altura"]]
lista_medidas$al

[1] 1.5

[1] 1.5

## Data Frame

Conjunto de vectores de la misma longitud. Cada vector puede ser de un tipo diferente.

In [244]:
plt <- c("Bollo","Palomitas","Limón","Ginebra","Noodles","Caramelo","Patatas fritas","Naranja","Ternera","Cerdo","Sopa")
cal <-c(150,200,10,20,200,5,500,15,450,460,30)

In [245]:
idx<- 5 
paste("Elemento",idx,":",plt[idx],"-",cal[idx],"cal")

[1] "Elemento 5 : Noodles - 200 cal"

In [246]:
comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = F)
comidas

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

In [247]:
str(comidas)

'data.frame':	11 obs. of  3 variables:
 $ plato   : chr  "Bollo" "Palomitas" "Limón" "Ginebra" ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : chr  "Dulce" "Salado" "Ácido" "Amargo" ...


### Acceso a elementos de un data frame

Acceso por filas:

In [248]:
comidas[2:3,]

plato     calorias sabor 
2 Palomitas 200      Salado
3 Limón      10      Ácido

In [249]:
comidas[c(-1,-3,-5,-10,-11),]

plato          calorias sabor 
2 Palomitas      200      Salado
4 Ginebra         20      Amargo
6 Caramelo         5      Dulce 
7 Patatas fritas 500      Salado
8 Naranja         15      Ácido 
9 Ternera        450      Umami

Acceso por columnas:

In [250]:
comidas[,c("plato","calorias")]

plato          calorias
1  Bollo          150     
2  Palomitas      200     
3  Limón           10     
4  Ginebra         20     
5  Noodles        200     
6  Caramelo         5     
7  Patatas fritas 500     
8  Naranja         15     
9  Ternera        450     
10 Cerdo          460     
11 Sopa            30

Se puede usar el símbolo **$** para acceder a una columna.  
Las siguientes dos llamadas son equivalentes:

In [255]:
comidas$plato

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [252]:
comidas[,"plato"]

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [253]:
comidas[,1]

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [258]:
comidas[,c(-1,-2)]

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

In [259]:
comidas$plato[2:3]

[1] "Palomitas" "Limón"

In [262]:
comidas[2:3,c("plato")]

[1] "Palomitas" "Limón"

In [267]:
colnames(comidas)
rownames(comidas)

[1] "plato"    "calorias" "sabor"

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11"

Número de filas que tiene un dataframe:

In [271]:
nrow(comidas)

[1] 11

Número de columnasa de un dataframe:

In [273]:
ncol(comidas)

[1] 3

También podemos dar nombres a las filas

In [274]:
rownames(comidas)<-paste0("comida",1:nrow(comidas))
comidas

plato          calorias sabor 
comida1  Bollo          150      Dulce 
comida2  Palomitas      200      Salado
comida3  Limón           10      Ácido 
comida4  Ginebra         20      Amargo
comida5  Noodles        200      Umami 
comida6  Caramelo         5      Dulce 
comida7  Patatas fritas 500      Salado
comida8  Naranja         15      Ácido 
comida9  Ternera        450      Umami 
comida10 Cerdo          460      Umami 
comida11 Sopa            30      Salado

In [275]:
comidas["comida5","calorias"]

[1] 200

In [276]:
comidas[5,"calorias"]

[1] 200

In [277]:
comidas[c(4,2),c(3,2,1)]

sabor  calorias plato    
comida4 Amargo  20      Ginebra  
comida2 Salado 200      Palomitas

El nombre de las columnas y de las filas se puede obtener y modificar con las funciones **colnames()** y **rownames()**.

In [278]:
colnames(comidas)
rownames(comidas)

[1] "plato"    "calorias" "sabor"

[1] "comida1"  "comida2"  "comida3"  "comida4"  "comida5"  "comida6" 
 [7] "comida7"  "comida8"  "comida9"  "comida10" "comida11"

### Dataset con variable categoricas 

In [279]:
comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = T)
comidas
str(comidas)

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

'data.frame':	11 obs. of  3 variables:
 $ plato   : Factor w/ 11 levels "Bollo","Caramelo",..: 1 8 5 4 7 2 9 6 11 3 ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


## Arrays 3D

Se pueden crear arrays N-dimensionales con la función array

In [282]:
arr<-array(1:12,dim = c(3,2,2))
arr
str(arr)

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

 int [1:3, 1:2, 1:2] 1 2 3 4 5 6 7 8 9 10 ...


El acceso a elementos es similar al de las matrices

In [283]:
arr[1,2,1]

[1] 4

In [284]:
arr[1,,]

[,1] [,2]
[1,] 1     7  
[2,] 4    10

In [285]:
arr[2,,]

[,1] [,2]
[1,] 2     8  
[2,] 5    11

In [286]:
arr[3,,]

[,1] [,2]
[1,] 3     9  
[2,] 6    12

In [287]:
arr[4,,]

ERROR: Error in arr[4, , ]: subscript out of bounds


In [288]:
arr[,2,]

[,1] [,2]
[1,] 4    10  
[2,] 5    11  
[3,] 6    12

## Fechas

Existen dos objetos para almacenar fechas en R.

* Posixct es recubrimiento sobre un timestamp en segundos.
* Posixlt es una lista de objetos que contiene la información de la fecha

In [300]:
d1<-as.POSIXct("2018-10-5 15:40")
d2<-as.POSIXct("1/10/2018 17:33",format="%m/%d/%Y",tz="CET")

d1
d2

[1] "2018-10-05 15:40:00 UTC"

[1] "2018-01-10 CET"

In [295]:
paste("La fecha actual es: ",Sys.time())

[1] "La fecha actual es:  2019-07-08 21:39:07"

In [290]:
str(d1)

 POSIXct[1:1], format: "2018-10-05 15:40:00"


In [298]:
?as.POSIXct

In [301]:
class(d1)

[1] "POSIXct" "POSIXt"

In [302]:
unclass(d1)

[1] 1538754000
attr(,"tzone")
[1] ""

In [308]:
d1
d1+60*60*24

[1] "2018-10-05 15:40:00 UTC"

[1] "2018-10-06 15:40:00 UTC"

In [311]:
d3<-as.POSIXlt("2018-4-5")
d3
class(d3)

[1] "2018-04-05 UTC"

[1] "POSIXlt" "POSIXt"

In [312]:
d3

[1] "2018-04-05 UTC"

In [313]:
d3$mday<-6

In [314]:
d3

[1] "2018-04-06 UTC"

In [310]:
str(d3)

 POSIXlt[1:1], format: "2018-04-05"


In [315]:
unclass(d3)

$sec
[1] 0

$min
[1] 0

$hour
[1] 0

$mday
[1] 6

$mon
[1] 3

$year
[1] 118

$wday
[1] 4

$yday
[1] 94

$isdst
[1] 0

$zone
[1] "UTC"

$gmtoff
[1] NA

In [320]:
d3$mon<-0
d3

[1] "2018-01-06 UTC"

In [319]:
#c(as.POSIXct("2018-01-01"),as.POSIXct("2018-01-02"),as.POSIXct("2018-01-03"))
str(c(as.POSIXlt("2018-01-01"),as.POSIXlt("2018-01-02"),as.POSIXlt("2018-01-03")))

 POSIXlt[1:3], format: "2018-01-01" "2018-01-02" "2018-01-03"


In [317]:
df<-data.frame(fecha=c(as.POSIXlt("2018-01-01"),as.POSIXlt("2018-01-02"),as.POSIXlt("2018-01-03")))
str(df)


'data.frame':	3 obs. of  1 variable:
 $ fecha: POSIXct, format: "2018-01-01" "2018-01-02" ...


## Valores no disponibles / Missing Values

Son valores para los cuales no tenemos ninguna medida, se representan con un NA.

Pertenecen a valores perdidos que no se han podido recuperar, errores de medida, perdidas de datos, etc..

En R los detectamos con:

is.na(x)
y podemos reemplazar su valor con la media, moda, mediana, etc...

o simplemente eliminarlos: na.omit(x)

Si estamos trabajando con series temporales es posible que queramos hacer una interpolación de los valores perdidos:

zoo::na.approx(x)

In [321]:
NA

[1] NA

In [341]:
data<-c(1,3,NA,6)
data

[1]  1  3 NA  6

In [342]:
data[c(FALSE,TRUE,TRUE,FALSE)]

[1]  3 NA

In [350]:
is.na(data)

[1] FALSE FALSE  TRUE FALSE

In [344]:
na.omit(data)

[1] 1 3 6
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"

In [345]:
paste("El número de elementos con NA:",length(data[is.na(data)]))

[1] "El número de elementos con NA: 1"

In [346]:
!is.na(data)

[1]  TRUE  TRUE FALSE  TRUE

In [347]:
paste("El número de elementos que NO son NA:",length(data[!is.na(data)]))

[1] "El número de elementos que NO son NA: 3"

In [348]:
data[1]<-10
data

[1] 10  3 NA  6

In [351]:
data[is.na(data)] <- 28
data

[1] 10  3 28  6

## Ejemplo datos reales


#### Dataset coches

Partimos del dataset de seguro de automóviles que podemos descargar de:

https://archive.ics.uci.edu/ml/datasets/Automobile


In [385]:
autos<-read.csv("./data//imports-85.data", col.names = c("risk", "normalized_losses", 
                                                         "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"),sep=",")

In [386]:
head(autos)

risk normalized_losses make        fuel_type aspiration num_doors body_style 
1 3    ?                 alfa-romero gas       std        two       convertible
2 1    ?                 alfa-romero gas       std        two       hatchback  
3 2    164               audi        gas       std        four      sedan      
4 2    164               audi        gas       std        four      sedan      
5 2    ?                 audi        gas       std        two       sedan      
6 1    158               audi        gas       std        four      sedan      
  drive_wheels engine_location wheel_base ⋯ engine_size fuel_system bore stroke
1 rwd          front            88.6      ⋯ 130         mpfi        3.47 2.68  
2 rwd          front            94.5      ⋯ 152         mpfi        2.68 3.47  
3 fwd          front            99.8      ⋯ 109         mpfi        3.19 3.40  
4 4wd          front            99.4      ⋯ 136         mpfi        3.19 3.40  
5 fwd          front            99.8      ⋯ 136         mpfi        3.19 3.40  
6 fwd          front           105.8      ⋯ 136         mpfi        3.19 3.40  
  compression_ratio horsepower peak_rpm city_mpg highway_mpg price
1  9.0              111        5000     21       27          16500
2  9.0              154        5000     19       26          16500
3 10.0              102        5500     24       30          13950
4  8.0              115        5500     18       22          17450
5  8.5              110        5500     19       25          15250
6  8.5              110        5500     19       25          17710

In [387]:
str(autos)

'data.frame':	204 obs. of  26 variables:
 $ risk             : int  3 1 2 2 2 1 1 1 0 2 ...
 $ normalized_losses: Factor w/ 52 levels "?","101","102",..: 1 1 29 29 1 27 1 27 1 33 ...
 $ make             : Factor w/ 22 levels "alfa-romero",..: 1 1 2 2 2 2 2 2 2 3 ...
 $ fuel_type        : Factor w/ 2 levels "diesel","gas": 2 2 2 2 2 2 2 2 2 2 ...
 $ aspiration       : Factor w/ 2 levels "std","turbo": 1 1 1 1 1 1 1 2 2 1 ...
 $ num_doors        : Factor w/ 3 levels "?","four","two": 3 3 2 2 3 2 2 2 3 3 ...
 $ body_style       : Factor w/ 5 levels "convertible",..: 1 3 4 4 4 4 5 4 3 4 ...
 $ drive_wheels     : Factor w/ 3 levels "4wd","fwd","rwd": 3 3 2 1 2 2 2 2 1 3 ...
 $ engine_location  : Factor w/ 2 levels "front","rear": 1 1 1 1 1 1 1 1 1 1 ...
 $ wheel_base       : num  88.6 94.5 99.8 99.4 99.8 ...
 $ length           : num  169 171 177 177 177 ...
 $ width            : num  64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 64.8 ...
 $ height           : num  48.8 52.4 54.3 54.3 53.1 5

In [388]:
summary(autos)

      risk         normalized_losses         make     fuel_type   aspiration 
 Min.   :-2.0000   ?      : 40       toyota    :32   diesel: 20   std  :167  
 1st Qu.: 0.0000   161    : 11       nissan    :18   gas   :184   turbo: 37  
 Median : 1.0000   91     :  8       mazda     :17                           
 Mean   : 0.8235   150    :  7       honda     :13                           
 3rd Qu.: 2.0000   104    :  6       mitsubishi:13                           
 Max.   : 3.0000   128    :  6       subaru    :12                           
                   (Other):126       (Other)   :99                           
 num_doors        body_style drive_wheels engine_location   wheel_base    
 ?   :  2   convertible: 5   4wd:  9      front:201       Min.   : 86.60  
 four:114   hardtop    : 8   fwd:120      rear :  3       1st Qu.: 94.50  
 two : 88   hatchback  :70   rwd: 75                      Median : 97.00  
            sedan      :96                                Mean   : 98.81  
 

Nos quedamos solo con las columnas: "price","horsepower","body_style","risk"

In [389]:
autos <- autos[,c( "price","horsepower","body_style","risk")]
head(autos)

price horsepower body_style  risk
1 16500 111        convertible 3   
2 16500 154        hatchback   1   
3 13950 102        sedan       2   
4 17450 115        sedan       2   
5 15250 110        sedan       2   
6 17710 110        sedan       1

In [390]:
str(autos)

'data.frame':	204 obs. of  4 variables:
 $ price     : Factor w/ 186 levels "?","10198","10245",..: 51 51 37 62 42 64 72 82 1 50 ...
 $ horsepower: Factor w/ 60 levels "?","100","101",..: 7 22 4 10 6 6 6 17 25 3 ...
 $ body_style: Factor w/ 5 levels "convertible",..: 1 3 4 4 4 4 5 4 3 4 ...
 $ risk      : int  3 1 2 2 2 1 1 1 0 2 ...


En este CSV cuando existe un valor desconocido lo han indicado con el caracter '?'. Por ese motivo la columna 'price' y 'horsepower' es factor en lugar de numeric.
Tenemos que indicarle a R que son NA:

In [391]:
autos$price[autos$price=='?']<-NA
autos$horsepower[autos$horsepower=='?']<-NA

Tenemos que convertir el factor de 'price' y 'horsepower' en valores numéricos:

In [392]:
str(autos)

'data.frame':	204 obs. of  4 variables:
 $ price     : Factor w/ 186 levels "?","10198","10245",..: 51 51 37 62 42 64 72 82 NA 50 ...
 $ horsepower: Factor w/ 60 levels "?","100","101",..: 7 22 4 10 6 6 6 17 25 3 ...
 $ body_style: Factor w/ 5 levels "convertible",..: 1 3 4 4 4 4 5 4 3 4 ...
 $ risk      : int  3 1 2 2 2 1 1 1 0 2 ...


In [380]:
autos$price<-as.numeric(as.character(autos$price))
autos$horsepower<-as.numeric(as.character(autos$horsepower))

In [381]:
str(autos)

'data.frame':	204 obs. of  4 variables:
 $ price     : num  16500 16500 13950 17450 15250 ...
 $ horsepower: num  111 154 102 115 110 110 110 140 160 101 ...
 $ body_style: Factor w/ 5 levels "convertible",..: 1 3 4 4 4 4 5 4 3 4 ...
 $ risk      : int  3 1 2 2 2 1 1 1 0 2 ...


In [382]:
summary(autos)

     price         horsepower          body_style      risk        
 Min.   : 5118   Min.   : 48.0   convertible: 5   Min.   :-2.0000  
 1st Qu.: 7775   1st Qu.: 70.0   hardtop    : 8   1st Qu.: 0.0000  
 Median :10270   Median : 95.0   hatchback  :70   Median : 1.0000  
 Mean   :13206   Mean   :104.2   sedan      :96   Mean   : 0.8235  
 3rd Qu.:16501   3rd Qu.:116.0   wagon      :25   3rd Qu.: 2.0000  
 Max.   :45400   Max.   :288.0                    Max.   : 3.0000  
 NA's   :4       NA's   :2                                         

In [383]:
autos[is.na(autos$price),]

price horsepower body_style risk
9   NA    160        hatchback  0   
44  NA     70        sedan      1   
45  NA     70        sedan      0   
129 NA    288        hatchback  1

#### Dataset cancer esófago


Se realizó un estudio retrospectivo de casos y controles de 200 casos masculinos de cáncer de esófago y 778 controles poblacionales en Ille-et-Vilanine (Francia). Los logaritmos de los riesgos relativos de desarrollar la enfermedad aumentan linealmente con el consumo diario de alcohol y tabaco de manera independiente. El efecto combinado de ambos se ajusta con un modelo multiplicativo que se propone. Este modelo podría ser aplicable a otras situaciones. Explica la proporción de sexos y las diferencias urbanas / rurales observadas en Ille-er-Vilaine. 

http://www.math.umd.edu/~evs/s430.old/Data/ESOPH.dat

Columnas:
* agegp: grupo de edad
* alcgp: consumo de alcohol
* tobgp: consumo de tabaco
* ncases: número de casos de cancer
* ncontrol: población de control


In [404]:
dfcancer<-read.csv("data/ESOPH.dat",skip=43,sep = "")
head(dfcancer)

agegp alcgp     tobgp    ncases ncontrols
1 25-34 0-39g/day 0-9g/day 0      40       
2 25-34 0-39g/day 10-19    0      10       
3 25-34 0-39g/day 20-29    0       6       
4 25-34 0-39g/day 30+      0       5       
5 25-34 40-79     0-9g/day 0      27       
6 25-34 40-79     10-19    0       7

In [405]:
str(dfcancer)

'data.frame':	88 obs. of  5 variables:
 $ agegp    : Factor w/ 6 levels "25-34","35-44",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ alcgp    : Factor w/ 4 levels "0-39g/day","120+",..: 1 1 1 1 3 3 3 3 4 4 ...
 $ tobgp    : Factor w/ 4 levels "0-9g/day","10-19",..: 1 2 3 4 1 2 3 4 1 2 ...
 $ ncases   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ ncontrols: int  40 10 6 5 27 7 4 7 2 1 ...


En ocasiones podemos convertir los factores en números. Com en este caso que sustituimos los rangos por su valor medio:

In [406]:
unique(dfcancer$agegp)

[1] 25-34 35-44 45-54 55-64 65-74 75+  
Levels: 25-34 35-44 45-54 55-64 65-74 75+

In [407]:
levels(dfcancer$agegp)

[1] "25-34" "35-44" "45-54" "55-64" "65-74" "75+"

In [408]:
ageVectors<-c(30,40,50,60,70,80)

In [412]:
as.numeric(dfcancer$agegp)

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3
[39] 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[77] 5 6 6 6 6 6 6 6 6 6 6 6

In [415]:
ageVectors[as.numeric(dfcancer$agegp)]

[1] 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 40 40 40 40 40 40 40 40 40 40
[26] 40 40 40 40 40 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 60 60 60 60
[51] 60 60 60 60 60 60 60 60 60 60 60 60 70 70 70 70 70 70 70 70 70 70 70 70 70
[76] 70 70 80 80 80 80 80 80 80 80 80 80 80

In [416]:
levels(dfcancer$agegp)[as.numeric(dfcancer$agegp)]

[1] "25-34" "25-34" "25-34" "25-34" "25-34" "25-34" "25-34" "25-34" "25-34"
[10] "25-34" "25-34" "25-34" "25-34" "25-34" "25-34" "35-44" "35-44" "35-44"
[19] "35-44" "35-44" "35-44" "35-44" "35-44" "35-44" "35-44" "35-44" "35-44"
[28] "35-44" "35-44" "35-44" "45-54" "45-54" "45-54" "45-54" "45-54" "45-54"
[37] "45-54" "45-54" "45-54" "45-54" "45-54" "45-54" "45-54" "45-54" "45-54"
[46] "45-54" "55-64" "55-64" "55-64" "55-64" "55-64" "55-64" "55-64" "55-64"
[55] "55-64" "55-64" "55-64" "55-64" "55-64" "55-64" "55-64" "55-64" "65-74"
[64] "65-74" "65-74" "65-74" "65-74" "65-74" "65-74" "65-74" "65-74" "65-74"
[73] "65-74" "65-74" "65-74" "65-74" "65-74" "75+"   "75+"   "75+"   "75+"  
[82] "75+"   "75+"   "75+"   "75+"   "75+"   "75+"   "75+"

In [417]:
unique(dfcancer$agegp)[as.numeric(dfcancer$agegp)]

[1] 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34
[13] 25-34 25-34 25-34 35-44 35-44 35-44 35-44 35-44 35-44 35-44 35-44 35-44
[25] 35-44 35-44 35-44 35-44 35-44 35-44 45-54 45-54 45-54 45-54 45-54 45-54
[37] 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 55-64 55-64
[49] 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64
[61] 55-64 55-64 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74
[73] 65-74 65-74 65-74 65-74 65-74 75+   75+   75+   75+   75+   75+   75+  
[85] 75+   75+   75+   75+  
Levels: 25-34 35-44 45-54 55-64 65-74 75+